[package]
name = "benchmark_rust_embed_database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.58"
btree-slab = "0.4.0"
dashmap = "5.3.4"
duckdb = { version = "0.4.0", features = ["bundled", "r2d2"] }
lmdb-rkv = "0.14.0"
num_cpus = "1.13.1"
parking_lot = "0.12.1"
persy = { version = "1.3.1", features = ["background_ops"] }
r2d2 = "0.8.10"
rand = "0.8.5"
rayon = "1.5.3"
rocksdb = { features = [
  "zstd"
], default-features = false }
rusty-leveldb = "1.0.2"
sled = "0.34.7"
yakv = "0.2.7"
